### ISSUE TITLE
Question about Uniformity loss formulation

### ISSUE THREAD

**Issue by msh9184** [SsnL/align_uniform#2]
Hello, thank you for the great resource.

In your implementation, uniformity loss is formulated as below:
![91417159-560cd080-e88b-11ea-8779-69d07055549d](https://user-images.githubusercontent.com/33674982/91428844-83607b00-e899-11ea-97c3-ee045871ed01.png)

When calculating the uniformity loss, you are computing the log-sum-exp of the input with l2-norm in units of samples, not pairwise.

I'm wondering if how the uniformity loss in your paper (logarithm of the average
pairwise Gaussian potential) is formulated as the code-version form.
![91418186-c536f480-e88c-11ea-9334-a98628dd5562](https://user-images.githubusercontent.com/33674982/91428920-88252f00-e899-11ea-8d39-273ba9f94c8c.png)

**Comment by ssnl** [comment]
Hi, `pdist` is pairwise distance, not l2-norm.

**Comment by msh9184** [comment]
Thanks a lot. I got it.

**Comment by msh9184** [comment]
Hello, Mr. Wang.
I have one more question.

The uniformity loss seems to be computed using some of the total pairs from (x,y)~p_data (i.e., [K(K-1)/2] *2 negative pairs.)
If my guess is correct, I ask if there is any reason for not using the whole pairs (2K(2K-1)/2 both pos & neg pairs).

Thank you.

**Comment by ssnl** [comment]
The positive pairs are sampled from a different joint distribution. If you use all, it will be a different quantity rather than the defined uniformity loss.

**Comment by msh9184** [comment]
Thank you for your answer.
If so, I wonder if it is okay to not include the rest of the negative pairs, e.g., negative pairs of x_i and y_j (i != j).

**Comment by ssnl** [comment]
Sure you can use those too, but you need to calculate a uniformity loss for each different `i` (where you enumerate over all `j` s), otherwise you have the same dependency problem we were talking above. You can definitely try that, although it would be more computationally costly and I am not sure if there will be benefits.

**Comment by msh9184** [comment]
Thank you so much!! :)

**Comment by adaxigua** [comment]
> Hi, `pdist` is pairwise distance, not l2-norm.
~~~
torch.dist(input, other, p=2)
p ([float], optional) – the norm to be computed
~~~
 
Already computed `torch.pdist(x, p=2)`, why continue to compute `pow(2)` ？ Is the step  `pow(2)` redundant？

**Comment by ssnl** [comment]
@msh9184 Because the formula is on squared distance, not raw distance

**Comment by GA-17a** [comment]
> The positive pairs are sampled from a different joint distribution. If you use all, it will be a different quantity rather than the defined uniformity loss.

Hi,
May I ask why the samples in a pair should be subject to the i.i.d. assumption in the defined uniformity loss?

**Comment by ssnl** [comment]
@GA-17a the uniformity loss is defined with iid samples because (1) this definition mathematically relates to uniform distribution (2) it is empirically a meaningful metric for measuring how uniform a distribution is (3) it also relates to the contrastive loss (essentially same way you same negative pairs). 

If you use pairs distributed as positive pair distribution, then it becomes just pushing positive features apart, something against alignment loss rather than enforcing uniformity. 

I wouldn’t say that it is an assumption. It is just the definition of the loss, and being to draw iid samples is already in contrastive learning (and very common), not something needed to be additionally assumed.

**Comment by sarahESL** [comment]
Why does `t` have to be positive?
